#!/bin/sh
set -e

if [ "$1" = remove ] || [ "$1" = purge ]; then
    for service in pvedaemon pveproxy pvestatd pvescheduler; do
        systemctl try-reload-or-restart "$service.service" 2>/dev/null || true
    done
fi

if [ "$1" = purge ]; then
    rm -rf /var/lib/urbackup-pve
fi

exit 0
